question = 'What does "rgba" stand for?'

answers = [
  "Relative Gradient Bisecting Angles",
  'Red, Green, Blue, Alpha',
  'Rounded Graphing Binormal Articulation',
  'Reticulated Globular Bifurcated Amalgam'
]

correct = 2
